version: '3.3'

services:
  exchange-rate-notifier-api:
    image: exchange-rate-notifier-api:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always