version: '3.3'

services:
  rate-service:
    image: rate-service:latest
    ports:
      - "8080:8080"
    build:
      context: ./rate-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rate-service-db
      - rabbitmq
  notification-service:
    image: notification-service:latest
    ports:
      - "8081:8080"
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rate-service-db
      - rabbitmq
  scheduler-service:
    image: scheduler-service:latest
    ports:
      - "8082:8080"
    build:
      context: ./scheduler-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rate-service-db
      - rabbitmq
  customer-service:
    image: customer-service:latest
    ports:
      - "8083:8080"
    build:
      context: ./scheduler-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rate-service-db
      - rabbitmq
  rate-service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
  customer-service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
  rabbitmq:
    image: rabbitmq:3.13.4-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    ports:
      - "15672:15672"
      - "5672:5672"
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    restart: always
    ports:
      - "8428:8428"
    command: -promscrape.config=/scrape-config.yml
    volumes:
      - ./scrape-config.yml:/scrape-config.yml