version: '3.3'

services:
  rate-service:
    image: rate-service:latest
    ports:
      - "8080:8080"
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
  notification-service:
    image: notification-service:latest
    ports:
      - "8081:8080"
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
  rabbitmq:
    image: rabbitmq:3.13.4-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "15672:15672"