global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'rate-service'
    static_configs:
      - targets: ['rate-service:8080']
  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8080']
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:8080']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']