server:
  port: 8080

crons:
  rate_notification: "*/30 * * * *"

rabbitmq:
  host: localhost
  port: 5672
  username: rmuser
  password: rmpassword
  queue:
    rate-notification-cron: rate-notification-cron