db:
  host: localhost
  port: 5433
  username: postgres
  password: admin
  name: postgres
  ssl_mode: disable
  driver_name: postgres
  search_path: scheduler-service

crons:
  rate_notification: "0 8 * * *"