definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: API server for notifying exchange rate
  title: Exchange rate notifier API
  version: "1.0"
paths:
  /api/subscribe:
    post:
      description: subscribe to notifications
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      responses:
        "200":
          description: ok
        "400":
          description: invalid email format
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "409":
          description: subscription already exists
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: failed to create subscription
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Subscribe to notifications
      tags:
      - subscription
  /api/unsubscribe:
    post:
      description: unsubscribe from notifications
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      responses:
        "200":
          description: ok
        "400":
          description: invalid email format
          schema:
            type: string
        "500":
          description: failed to delete subscription
          schema:
            type: string
      summary: Unsubscribe from notifications
      tags:
      - subscription
  /rate:
    get:
      consumes:
      - application/json
      description: Get the current exchange rate from the external API
      produces:
      - application/json
      responses:
        "200":
          description: Returns the current exchange rate
          schema:
            type: string
        "500":
          description: failed to get exchange rate
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get current exchange rate
      tags:
      - rate
swagger: "2.0"
