server:
  port: 8080

rabbitmq:
  host: localhost
  port: 5672
  username: rmuser
  password: rmpassword
  queue:
    mail: mail

mail:
  host: smtp.gmail.com
  port: 587
  username: bot880027@gmail.com
  password: "wgcf jgmo jrdo cxmg"